from pydantic import BaseModel, Field, ConfigDict, AliasChoices
from typing import List, Optional, Literal, Dict

class RelationalPersistence(BaseModel):
    """Configuración de persistencia relacional."""
    model_config = ConfigDict(populate_by_name=True)
    
    table: Optional[str] = None
    column: Optional[str] = None
    primary_key: bool = Field(default=False, alias="primary-key")
    autogenerated: bool = Field(default=False, alias="autogenerated")
    foreign_column: Optional[str] = Field(default=None, alias="foreign-column")
    join_table: Optional[str] = Field(default=None, validation_alias=AliasChoices("join-table", "intermediate-table", "intermediary-table"))
    join_column: Optional[str] = Field(default=None, alias="join-column")
    inverse_join_column: Optional[str] = Field(default=None, alias="inverse-join-column")
    relation_type: Optional[str] = Field(default=None, alias="relation-type")

class ModelAttribute(BaseModel):
    """Atributo de un modelo de dominio."""
    model_config = ConfigDict(populate_by_name=True)
    
    name: str
    type: str
    # Para arrays
    is_array: bool = Field(default=False, alias="is-array")
    items_type: Optional[str] = Field(default=None, alias="items-type")
    items_ref_model: Optional[str] = Field(default=None, alias="items-ref-model")
    ref_model: Optional[str] = Field(default=None, alias="ref-model")
    has_json_conversion: bool = Field(default=False, alias="has_json_conversion")
    is_exposed_in_schema: bool = Field(default=False, alias="is_exposed_in_schema")
    read_only: bool = Field(default=False, alias="read_only")
    write_only: bool = Field(default=False, alias="write_only")
    persistence: Optional[RelationalPersistence] = Field(default=None, alias="relational-persistence")
    has_json_conversion: bool = Field(default=False, alias="has-json-conversion")
    warning: Optional[str] = None

class ModelContract(BaseModel):
    """
    Contrato para un modelo dentro de x-apigen-models.
    Supports apigen-python format (table at root).
    """
    model_config = ConfigDict(populate_by_name=True)
    
    attributes: List[ModelAttribute]
    table: Optional[str] = None
    persistence: Optional[RelationalPersistence] = Field(default=None, alias="relational-persistence")
    
    @property
    def table_name(self) -> Optional[str]:
        """Get table name."""
        if self.table:
            return self.table
        if self.persistence and self.persistence.table:
            return self.persistence.table
        return None
    
    @property
    def has_persistence(self) -> bool:
        """Check if model has persistence configuration."""
        return self.table_name is not None

    @property
    def primary_key_attr(self) -> Optional[ModelAttribute]:
        for attr in self.attributes:
            if attr.persistence and attr.persistence.primary_key:
                return attr
        return None

    @property
    def primary_key_sa_type(self) -> str:
        """SQLAlchemy type name for PK (default Integer)."""
        from ..type_mapper import to_sa_pk_type
        pk = self.primary_key_attr
        if pk:
            return to_sa_pk_type(pk.type)
        return "Integer"

