sonar.exclusions=src/apigen_copier/template/**/*,src/apigen_copier/template_asyncapi/**/*,src/apigen_copier/partials/**/*,src/apigen_copier/partials_asyncapi/**/*
sonar.coverage.exclusions=src/apigen_copier/template/**/*,src/apigen_copier/template_asyncapi/**/*,src/apigen_copier/partials/**/*,src/apigen_copier/partials_asyncapi/**/*
