"""
TDD tests for the AsyncAPI code generator (Phase 2).

These tests define the EXPECTED behavior of the AsyncAPI copier BEFORE
the implementation exists. Each test class covers one generation concern.

Run: pytest tests/test_asyncapi_copier.py -v
"""
import sys
import os
import json
import shutil
import tempfile

import pytest

# ── path setup ──────────────────────────────────────────────────
sys.path.append(os.path.join(os.getcwd(), "package"))

# ── Fixtures ────────────────────────────────────────────────────

# Minimal valid project.json as produced by the Phase 1 AsyncAPI parser.
# Mirrors the structure of AsyncApiProjectSchema.model_dump().
MINIMAL_ASYNC_PROJECT_JSON = {
    "project": {
        "name": "test-async-service",
        "version": "1.0.0",
        "description": "Minimal test",
        "data-driver": "postgresql",
    },
    "default_content_type": "application/json",
    "servers": {
        "kafka-dev": {
            "host": "localhost:9092",
            "protocol": "kafka",
            "security": [],
        }
    },
    "channels": {
        "orderEvents": {
            "address": "orders.events",
            "parameters": {},
            "messages": {
                "OrderCreatedMsg": {
                    "x-apigen-binding": {"model": "Order", "action": "create"},
                    "payload": {
                        "type": "object",
                        "properties": {
                            "id": {"type": "string"},
                            "status": {"type": "string"},
                        },
                    },
                }
            },
        }
    },
    "operations": {
        "onOrderCreated": {
            "action": "receive",
            "channel": {
                "address": "orders.events",
                "parameters": {},
                "messages": {
                    "OrderCreatedMsg": {
                        "x-apigen-binding": {"model": "Order", "action": "create"},
                        "payload": {
                            "type": "object",
                            "properties": {
                                "id": {"type": "string"},
                                "status": {"type": "string"},
                            },
                        },
                    }
                },
            },
            "bindings": {"kafka": {"groupId": "order-service-group"}},
            "reply": None,
            "messages": [
                {
                    "x-apigen-binding": {"model": "Order", "action": "create"},
                    "payload": {
                        "type": "object",
                        "properties": {
                            "id": {"type": "string"},
                            "status": {"type": "string"},
                        },
                    },
                }
            ],
        }
    },
    "entities": {
        "Order": {
            "table": "orders",
            "attributes": [
                {
                    "name": "id",
                    "type": "String",
                    "relational-persistence": {"primary-key": True, "autogenerated": False},
                },
                {"name": "status", "type": "String"},
            ],
        }
    },
    "components": {
        "schemas": {
            "OrderDTO": {
                "type": "object",
                "properties": {
                    "id": {"type": "string"},
                    "status": {"type": "string"},
                },
            }
        }
    },
}


def _torture_project_json():
    """Full torture-spec project.json with all operation patterns."""
    base = json.loads(json.dumps(MINIMAL_ASYNC_PROJECT_JSON))  # deep copy

    # Add RabbitMQ server
    base["servers"]["rabbitmq-dev"] = {
        "host": "localhost:5672",
        "protocol": "amqp",
        "security": [{"userPassword": []}],
    }

    # Additional entities
    base["entities"]["User"] = {
        "table": "users",
        "attributes": [
            {"name": "id", "type": "String", "relational-persistence": {"primary-key": True}},
            {"name": "email", "type": "String"},
            {"name": "displayName", "type": "String"},
        ],
    }

    # ── More channels ──
    base["channels"]["userEvents"] = {
        "address": "ecommerce.users.lifecycle",
        "parameters": {},
        "messages": {
            "UserSignedUp": {
                "x-apigen-binding": {"model": "User", "action": "create"},
                "payload": {"$ref": "#/components/schemas/UserDTO"},
            }
        },
    }
    base["channels"]["notifications"] = {
        "address": "ecommerce.notifications.send",
        "parameters": {},
        "messages": {
            "NotifyMsg": {
                "x-apigen-binding": {"action": "custom"},
                "payload": {
                    "type": "object",
                    "properties": {
                        "channel": {"type": "string"},
                        "recipient": {"type": "string"},
                        "message": {"type": "string"},
                    },
                },
            }
        },
    }
    base["channels"]["inventoryCheckReq"] = {
        "address": "ecommerce.inventory.check",
        "parameters": {},
        "messages": {"CheckReq": {"payload": {"type": "object", "properties": {"productId": {"type": "string"}}}}},
    }
    base["channels"]["inventoryCheckRes"] = {
        "address": "ecommerce.inventory.response",
        "parameters": {},
        "messages": {
            "CheckRes": {
                "payload": {
                    "type": "object",
                    "properties": {
                        "productId": {"type": "string"},
                        "inStock": {"type": "boolean"},
                        "availableQty": {"type": "integer"},
                    },
                }
            }
        },
    }
    base["channels"]["orderConfirmed"] = {
        "address": "ecommerce.orders.confirmed",
        "parameters": {},
        "messages": {
            "ConfirmedMsg": {
                "x-apigen-binding": {"model": "Order", "action": "update"},
                "payload": {"$ref": "#/components/schemas/OrderDTO"},
            }
        },
    }

    # ── More operations (CRUD update, delete, custom, RPC, publisher) ──
    base["operations"]["onOrderUpdated"] = {
        "action": "receive",
        "channel": base["channels"]["orderEvents"],
        "bindings": {"kafka": {"groupId": "order-service-group"}},
        "reply": None,
        "messages": [
            {
                "x-apigen-binding": {"model": "Order", "action": "update"},
                "payload": {"type": "object", "properties": {"id": {"type": "string"}, "status": {"type": "string"}}},
            }
        ],
    }
    base["operations"]["onOrderDeleted"] = {
        "action": "receive",
        "channel": base["channels"]["orderEvents"],
        "bindings": {"kafka": {"groupId": "order-service-group"}},
        "reply": None,
        "messages": [
            {
                "x-apigen-binding": {"model": "Order", "action": "delete"},
                "payload": {"type": "object", "properties": {"id": {"type": "string"}}},
            }
        ],
    }
    base["operations"]["onUserSignedUp"] = {
        "action": "receive",
        "channel": base["channels"]["userEvents"],
        "bindings": {"kafka": {"groupId": "user-service-group"}},
        "reply": None,
        "messages": [
            {
                "x-apigen-binding": {"model": "User", "action": "create"},
                "payload": {"type": "object", "properties": {"id": {"type": "string"}, "email": {"type": "string"}}},
            }
        ],
    }
    base["operations"]["onNotification"] = {
        "action": "receive",
        "channel": base["channels"]["notifications"],
        "bindings": {"kafka": {"groupId": "notification-service-group"}},
        "reply": None,
        "messages": [
            {
                "x-apigen-binding": {"action": "custom"},
                "payload": {
                    "type": "object",
                    "properties": {"channel": {"type": "string"}, "recipient": {"type": "string"}, "message": {"type": "string"}},
                },
            }
        ],
    }
    base["operations"]["requestInventoryCheck"] = {
        "action": "send",
        "channel": base["channels"]["inventoryCheckReq"],
        "bindings": {},
        "reply": {"channel": base["channels"]["inventoryCheckRes"]},
        "messages": [{"payload": {"type": "object", "properties": {"productId": {"type": "string"}}}}],
    }
    base["operations"]["publishOrderConfirmed"] = {
        "action": "send",
        "channel": base["channels"]["orderConfirmed"],
        "bindings": {},
        "reply": None,
        "messages": [
            {
                "x-apigen-binding": {"model": "Order", "action": "update"},
                "payload": {"type": "object", "properties": {"id": {"type": "string"}, "status": {"type": "string"}}},
            }
        ],
    }

    # ── More schemas ──
    base["components"]["schemas"]["UserDTO"] = {
        "type": "object",
        "properties": {
            "id": {"type": "string"},
            "email": {"type": "string"},
            "displayName": {"type": "string"},
        },
    }

    return base


# ════════════════════════════════════════════════════════════════
# §1  SCHEMA VALIDATION
# ════════════════════════════════════════════════════════════════

class TestAsyncSchemaValidation:
    """Verify that the AsyncAPI project schema model accepts / rejects data correctly."""

    def test_schema_accepts_valid_project_json(self):
        """A well-formed project.json must parse without errors."""
        from apigen_copier.async_schemas import AsyncAPIProjectSchema

        schema = AsyncAPIProjectSchema(**MINIMAL_ASYNC_PROJECT_JSON, output_dir="/tmp/out")
        assert schema.project.name == "test-async-service"
        assert "kafka-dev" in schema.servers
        assert "Order" in schema.entities

    def test_schema_rejects_missing_operations(self):
        """project.json without operations block must fail."""
        from apigen_copier.async_schemas import AsyncAPIProjectSchema

        data = json.loads(json.dumps(MINIMAL_ASYNC_PROJECT_JSON))
        del data["operations"]
        with pytest.raises(Exception):
            AsyncAPIProjectSchema(**data, output_dir="/tmp/out")

    def test_schema_rejects_missing_servers(self):
        """project.json without servers block must fail."""
        from apigen_copier.async_schemas import AsyncAPIProjectSchema

        data = json.loads(json.dumps(MINIMAL_ASYNC_PROJECT_JSON))
        del data["servers"]
        with pytest.raises(Exception):
            AsyncAPIProjectSchema(**data, output_dir="/tmp/out")

    def test_schema_detects_primary_broker_protocol(self):
        """The schema should expose the primary broker's protocol (first server)."""
        from apigen_copier.async_schemas import AsyncAPIProjectSchema

        schema = AsyncAPIProjectSchema(**MINIMAL_ASYNC_PROJECT_JSON, output_dir="/tmp/out")
        primary = list(schema.servers.values())[0]
        assert primary.protocol == "kafka"

    def test_schema_accepts_full_torture_spec(self):
        """The full torture spec project.json must parse without errors."""
        from apigen_copier.async_schemas import AsyncAPIProjectSchema

        data = _torture_project_json()
        schema = AsyncAPIProjectSchema(**data, output_dir="/tmp/out")
        assert len(schema.operations) == 7
        assert len(schema.entities) == 2
        assert len(schema.servers) == 2


# ════════════════════════════════════════════════════════════════
# §2  HANDLER GENERATION  (action: receive)
# ════════════════════════════════════════════════════════════════

class TestHandlerGeneration:
    """Verify that receive operations generate correct handler files."""

    @pytest.fixture(autouse=True)
    def setup(self, tmp_path):
        self.output_dir = str(tmp_path / "generated")
        self.data = _torture_project_json()

    def _generate(self):
        from apigen_copier.async_core import generate_from_async_schema
        from apigen_copier.async_schemas import AsyncAPIProjectSchema

        schema = AsyncAPIProjectSchema(**self.data, output_dir=self.output_dir)
        return generate_from_async_schema(schema)

    def test_crud_create_handler_generated(self):
        """receive + x-apigen-binding.action=create → handler file with create logic."""
        result = self._generate()
        # Expect a handler file for the onOrderCreated operation
        handler_dir = os.path.join(result, "src", "handlers")
        assert os.path.isdir(handler_dir), f"handlers dir not found: {handler_dir}"
        # Find a handler file that contains create service call
        handler_files = [f for f in os.listdir(handler_dir) if f.endswith(".py") and f != "__init__.py"]
        assert len(handler_files) > 0, "No handler files generated"
        # At least one handler should contain a create call
        all_content = ""
        for hf in handler_files:
            with open(os.path.join(handler_dir, hf)) as fh:
                all_content += fh.read()
        assert "create" in all_content.lower(), "No create handler logic found"

    def test_crud_update_handler_generated(self):
        """receive + x-apigen-binding.action=update → handler with update logic."""
        result = self._generate()
        handler_dir = os.path.join(result, "src", "handlers")
        all_content = ""
        for hf in os.listdir(handler_dir):
            if hf.endswith(".py") and hf != "__init__.py":
                with open(os.path.join(handler_dir, hf)) as fh:
                    all_content += fh.read()
        assert "update" in all_content.lower(), "No update handler logic found"

    def test_crud_delete_handler_generated(self):
        """receive + x-apigen-binding.action=delete → handler with delete logic."""
        result = self._generate()
        handler_dir = os.path.join(result, "src", "handlers")
        all_content = ""
        for hf in os.listdir(handler_dir):
            if hf.endswith(".py") and hf != "__init__.py":
                with open(os.path.join(handler_dir, hf)) as fh:
                    all_content += fh.read()
        assert "delete" in all_content.lower(), "No delete handler logic found"

    def test_custom_handler_generates_stub(self):
        """receive + x-apigen-binding.action=custom → stub handler with TODO."""
        result = self._generate()
        handler_dir = os.path.join(result, "src", "handlers")
        all_content = ""
        for hf in os.listdir(handler_dir):
            if hf.endswith(".py") and hf != "__init__.py":
                with open(os.path.join(handler_dir, hf)) as fh:
                    all_content += fh.read()
        assert "todo" in all_content.lower() or "custom" in all_content.lower(), \
            "No custom handler stub found"

    def test_handler_has_correct_topic_subscription(self):
        """Each handler must subscribe to the correct channel address."""
        result = self._generate()
        handler_dir = os.path.join(result, "src", "handlers")
        all_content = ""
        for hf in os.listdir(handler_dir):
            if hf.endswith(".py") and hf != "__init__.py":
                with open(os.path.join(handler_dir, hf)) as fh:
                    all_content += fh.read()
        # The order handlers should reference the orders topic
        assert "orders.events" in all_content or "orderEvents" in all_content, \
            "Handler does not reference correct topic"

    def test_handler_uses_pydantic_dto(self):
        """Handlers should receive typed Pydantic DTOs, not raw dicts."""
        result = self._generate()
        handler_dir = os.path.join(result, "src", "handlers")
        all_content = ""
        for hf in os.listdir(handler_dir):
            if hf.endswith(".py") and hf != "__init__.py":
                with open(os.path.join(handler_dir, hf)) as fh:
                    all_content += fh.read()
        # Should import or reference a DTO class
        assert "DTO" in all_content or "BaseModel" in all_content or "dto" in all_content, \
            "Handlers should use Pydantic DTOs"


# ════════════════════════════════════════════════════════════════
# §3  PUBLISHER GENERATION  (action: send, no reply)
# ════════════════════════════════════════════════════════════════

class TestPublisherGeneration:
    """Verify that send operations without reply generate publisher files."""

    @pytest.fixture(autouse=True)
    def setup(self, tmp_path):
        self.output_dir = str(tmp_path / "generated")
        self.data = _torture_project_json()

    def _generate(self):
        from apigen_copier.async_core import generate_from_async_schema
        from apigen_copier.async_schemas import AsyncAPIProjectSchema

        schema = AsyncAPIProjectSchema(**self.data, output_dir=self.output_dir)
        return generate_from_async_schema(schema)

    def test_send_operation_generates_publisher(self):
        """action: send without reply → publisher file."""
        result = self._generate()
        publisher_dir = os.path.join(result, "src", "publishers")
        assert os.path.isdir(publisher_dir), f"publishers dir not found"
        py_files = [f for f in os.listdir(publisher_dir) if f.endswith(".py") and f != "__init__.py"]
        assert len(py_files) > 0, "No publisher files generated"

    def test_publisher_has_correct_topic(self):
        """Publisher must reference the target channel address."""
        result = self._generate()
        publisher_dir = os.path.join(result, "src", "publishers")
        all_content = ""
        for pf in os.listdir(publisher_dir):
            if pf.endswith(".py") and pf != "__init__.py":
                with open(os.path.join(publisher_dir, pf)) as fh:
                    all_content += fh.read()
        assert "confirmed" in all_content.lower() or "orderConfirmed" in all_content, \
            "Publisher doesn't reference correct topic"

    def test_fire_and_forget_no_reply(self):
        """publishOrderConfirmed has no reply → no reply listener generated."""
        result = self._generate()
        publisher_dir = os.path.join(result, "src", "publishers")
        all_content = ""
        for pf in os.listdir(publisher_dir):
            if pf.endswith(".py") and pf != "__init__.py":
                with open(os.path.join(publisher_dir, pf)) as fh:
                    all_content += fh.read()
        # Should NOT contain reply/response handling for fire-and-forget
        assert "reply" not in all_content.lower() or "no reply" in all_content.lower(), \
            "Fire-and-forget publisher shouldn't have reply logic"


# ════════════════════════════════════════════════════════════════
# §4  RPC REQUEST-REPLY GENERATION  (action: send, with reply)
# ════════════════════════════════════════════════════════════════

class TestRPCGeneration:
    """Verify that send operations WITH reply generate RPC client code."""

    @pytest.fixture(autouse=True)
    def setup(self, tmp_path):
        self.output_dir = str(tmp_path / "generated")
        self.data = _torture_project_json()

    def _generate(self):
        from apigen_copier.async_core import generate_from_async_schema
        from apigen_copier.async_schemas import AsyncAPIProjectSchema

        schema = AsyncAPIProjectSchema(**self.data, output_dir=self.output_dir)
        return generate_from_async_schema(schema)

    def test_rpc_generates_client_file(self):
        """action: send + reply → RPC client file generated."""
        result = self._generate()
        # RPC clients can live in publishers/ or a dedicated rpc/ dir
        src_dir = os.path.join(result, "src")
        all_py = []
        for root, dirs, files in os.walk(src_dir):
            for f in files:
                if f.endswith(".py"):
                    all_py.append(os.path.join(root, f))
        all_content = ""
        for fp in all_py:
            with open(fp) as fh:
                all_content += fh.read()
        assert "inventory" in all_content.lower(), "No RPC client for inventory check"

    def test_rpc_has_request_channel(self):
        """RPC client must publish to the request channel."""
        result = self._generate()
        src_dir = os.path.join(result, "src")
        all_content = ""
        for root, dirs, files in os.walk(src_dir):
            for f in files:
                if f.endswith(".py"):
                    with open(os.path.join(root, f)) as fh:
                        all_content += fh.read()
        assert "inventory.check" in all_content or "inventoryCheckReq" in all_content, \
            "RPC client doesn't reference request channel"

    def test_rpc_has_reply_channel(self):
        """RPC client must listen on the reply channel."""
        result = self._generate()
        src_dir = os.path.join(result, "src")
        all_content = ""
        for root, dirs, files in os.walk(src_dir):
            for f in files:
                if f.endswith(".py"):
                    with open(os.path.join(root, f)) as fh:
                        all_content += fh.read()
        assert "inventory.response" in all_content or "inventoryCheckRes" in all_content, \
            "RPC client doesn't reference reply channel"


# ════════════════════════════════════════════════════════════════
# §5  BROKER CONFIG GENERATION
# ════════════════════════════════════════════════════════════════

class TestBrokerConfig:
    """Verify broker configuration files are generated correctly."""

    @pytest.fixture(autouse=True)
    def setup(self, tmp_path):
        self.output_dir = str(tmp_path / "generated")

    def _generate(self, data):
        from apigen_copier.async_core import generate_from_async_schema
        from apigen_copier.async_schemas import AsyncAPIProjectSchema

        schema = AsyncAPIProjectSchema(**data, output_dir=self.output_dir)
        return generate_from_async_schema(schema)

    def test_kafka_config_generated(self):
        """Primary server with protocol=kafka → KafkaBroker config."""
        data = json.loads(json.dumps(MINIMAL_ASYNC_PROJECT_JSON))
        result = self._generate(data)
        broker_dir = os.path.join(result, "src", "broker")
        assert os.path.isdir(broker_dir), "broker/ dir not found"
        all_content = ""
        for f in os.listdir(broker_dir):
            if f.endswith(".py"):
                with open(os.path.join(broker_dir, f)) as fh:
                    all_content += fh.read()
        assert "kafka" in all_content.lower(), "Kafka broker config not found"

    def test_rabbitmq_config_generated(self):
        """Primary server with protocol=amqp → RabbitBroker config."""
        data = json.loads(json.dumps(MINIMAL_ASYNC_PROJECT_JSON))
        # Change primary server to RabbitMQ
        data["servers"] = {
            "rabbitmq-dev": {
                "host": "localhost:5672",
                "protocol": "amqp",
                "security": [],
            }
        }
        result = self._generate(data)
        broker_dir = os.path.join(result, "src", "broker")
        all_content = ""
        for f in os.listdir(broker_dir):
            if f.endswith(".py"):
                with open(os.path.join(broker_dir, f)) as fh:
                    all_content += fh.read()
        assert "rabbit" in all_content.lower() or "amqp" in all_content.lower(), \
            "RabbitMQ broker config not found"

    def test_security_env_vars_included(self):
        """Broker with security → config references env vars for credentials."""
        data = json.loads(json.dumps(MINIMAL_ASYNC_PROJECT_JSON))
        data["servers"]["kafka-dev"]["security"] = [{"saslScram": []}]
        result = self._generate(data)
        broker_dir = os.path.join(result, "src", "broker")
        all_content = ""
        for f in os.listdir(broker_dir):
            if f.endswith(".py"):
                with open(os.path.join(broker_dir, f)) as fh:
                    all_content += fh.read()
        # Should reference environment variables for security
        assert "BROKER" in all_content or "SASL" in all_content or "os.environ" in all_content or "getenv" in all_content, \
            "Security config should reference env vars"


# ════════════════════════════════════════════════════════════════
# §6  DTO GENERATION
# ════════════════════════════════════════════════════════════════

class TestDTOGeneration:
    """Verify that message payload schemas generate Pydantic DTOs."""

    @pytest.fixture(autouse=True)
    def setup(self, tmp_path):
        self.output_dir = str(tmp_path / "generated")
        self.data = _torture_project_json()

    def _generate(self):
        from apigen_copier.async_core import generate_from_async_schema
        from apigen_copier.async_schemas import AsyncAPIProjectSchema

        schema = AsyncAPIProjectSchema(**self.data, output_dir=self.output_dir)
        return generate_from_async_schema(schema)

    def test_dto_from_payload_schema(self):
        """components.schemas.OrderDTO → generated Pydantic model."""
        result = self._generate()
        dto_dir = os.path.join(result, "src", "application", "dtos")
        assert os.path.isdir(dto_dir), "dtos/ dir not found"
        py_files = [f for f in os.listdir(dto_dir) if f.endswith(".py") and f != "__init__.py"]
        assert len(py_files) > 0, "No DTO files generated"

    def test_dto_has_correct_fields(self):
        """OrderDTO should have id and status fields."""
        result = self._generate()
        dto_dir = os.path.join(result, "src", "application", "dtos")
        all_content = ""
        for f in os.listdir(dto_dir):
            if f.endswith(".py") and f != "__init__.py":
                with open(os.path.join(dto_dir, f)) as fh:
                    all_content += fh.read()
        assert "id" in all_content, "DTO missing 'id' field"
        assert "status" in all_content, "DTO missing 'status' field"

    def test_dto_types_mapped_correctly(self):
        """JSON schema types should map to Python types (string→str, integer→int, boolean→bool)."""
        result = self._generate()
        dto_dir = os.path.join(result, "src", "application", "dtos")
        all_content = ""
        for f in os.listdir(dto_dir):
            if f.endswith(".py") and f != "__init__.py":
                with open(os.path.join(dto_dir, f)) as fh:
                    all_content += fh.read()
        # At minimum, string types should be present as 'str'
        assert "str" in all_content, "String type not mapped to Python 'str'"


# ════════════════════════════════════════════════════════════════
# §7  DOMAIN + INFRASTRUCTURE (reused from REST)
# ════════════════════════════════════════════════════════════════

class TestDomainInfraGeneration:
    """Verify that domain models, entities, repositories, services, and mappers
    are generated for each x-apigen-models entity (reusing REST templates)."""

    @pytest.fixture(autouse=True)
    def setup(self, tmp_path):
        self.output_dir = str(tmp_path / "generated")
        self.data = _torture_project_json()

    def _generate(self):
        from apigen_copier.async_core import generate_from_async_schema
        from apigen_copier.async_schemas import AsyncAPIProjectSchema

        schema = AsyncAPIProjectSchema(**self.data, output_dir=self.output_dir)
        return generate_from_async_schema(schema)

    def test_domain_models_generated(self):
        """Each entity should have a domain model."""
        result = self._generate()
        domain_dir = os.path.join(result, "src", "domain", "models")
        assert os.path.isdir(domain_dir), "domain/models/ not found"
        all_dirs = os.listdir(domain_dir)
        # Should have at least Order and User dirs/files
        all_names = " ".join(all_dirs).lower()
        assert "order" in all_names, "Order domain model not found"
        assert "user" in all_names, "User domain model not found"

    def test_infra_entities_generated(self):
        """Each entity should have a SQLAlchemy entity."""
        result = self._generate()
        entity_dir = os.path.join(result, "src", "infrastructure", "entities")
        assert os.path.isdir(entity_dir), "infrastructure/entities/ not found"

    def test_repositories_generated(self):
        """Each entity should have a repository."""
        result = self._generate()
        repo_dir = os.path.join(result, "src", "infrastructure", "repository")
        assert os.path.isdir(repo_dir), "infrastructure/repository/ not found"

    def test_services_generated(self):
        """Each entity should have a service."""
        result = self._generate()
        service_dir = os.path.join(result, "src", "infrastructure", "service")
        assert os.path.isdir(service_dir), "infrastructure/service/ not found"

    def test_mappers_generated(self):
        """Each entity should have a mapper."""
        result = self._generate()
        mapper_dir = os.path.join(result, "src", "infrastructure", "mappers")
        assert os.path.isdir(mapper_dir), "infrastructure/mappers/ not found"


# ════════════════════════════════════════════════════════════════
# §8  FULL PIPELINE
# ════════════════════════════════════════════════════════════════

class TestFullPipeline:
    """End-to-end: project.json → complete generated project."""

    @pytest.fixture(autouse=True)
    def setup(self, tmp_path):
        self.output_dir = str(tmp_path / "generated")
        self.data = _torture_project_json()

    def _generate(self):
        from apigen_copier.async_core import generate_from_async_schema
        from apigen_copier.async_schemas import AsyncAPIProjectSchema

        schema = AsyncAPIProjectSchema(**self.data, output_dir=self.output_dir)
        return generate_from_async_schema(schema)

    def test_generated_project_has_main_py(self):
        """The generated project must have a main.py entrypoint."""
        result = self._generate()
        main_py = os.path.join(result, "src", "main.py")
        assert os.path.isfile(main_py), "main.py not found"

    def test_main_uses_faststream(self):
        """main.py should import and use FastStream."""
        result = self._generate()
        main_py = os.path.join(result, "src", "main.py")
        with open(main_py) as f:
            content = f.read()
        assert "faststream" in content.lower(), "main.py should use FastStream"

    def test_generated_project_has_docker_compose(self):
        """The generated project must have a docker-compose.yml."""
        result = self._generate()
        compose = os.path.join(result, "docker-compose.yml")
        assert os.path.isfile(compose), "docker-compose.yml not found"

    def test_docker_compose_has_broker(self):
        """docker-compose.yml should include a broker service (Kafka or RabbitMQ)."""
        result = self._generate()
        compose = os.path.join(result, "docker-compose.yml")
        with open(compose) as f:
            content = f.read()
        assert "kafka" in content.lower() or "rabbitmq" in content.lower(), \
            "docker-compose must include broker service"

    def test_generated_project_has_pyproject_toml(self):
        """The generated project must have a pyproject.toml."""
        result = self._generate()
        pyproject = os.path.join(result, "pyproject.toml")
        assert os.path.isfile(pyproject), "pyproject.toml not found"

    def test_pyproject_has_faststream_dep(self):
        """pyproject.toml should list faststream as a dependency."""
        result = self._generate()
        pyproject = os.path.join(result, "pyproject.toml")
        with open(pyproject) as f:
            content = f.read()
        assert "faststream" in content, "pyproject.toml should have faststream dependency"

    def test_generated_project_has_dockerfile(self):
        """The generated project must have a Dockerfile."""
        result = self._generate()
        dockerfile = os.path.join(result, "Dockerfile")
        assert os.path.isfile(dockerfile), "Dockerfile not found"

    def test_dockerfile_uses_python_313(self):
        """Dockerfile should use python:3.13-slim."""
        result = self._generate()
        dockerfile = os.path.join(result, "Dockerfile")
        with open(dockerfile) as f:
            content = f.read()
        assert "python:3.13" in content, "Dockerfile should use Python 3.13"

    def test_generated_project_has_env_example(self):
        """The generated project must have a .env.example."""
        result = self._generate()
        env = os.path.join(result, ".env.example")
        assert os.path.isfile(env), ".env.example not found"

    def test_env_example_has_broker_vars(self):
        """The .env.example should include broker configuration variables."""
        result = self._generate()
        env = os.path.join(result, ".env.example")
        with open(env) as f:
            content = f.read()
        assert "BROKER" in content, ".env.example should have BROKER variables"

    def test_generated_project_has_database_config(self):
        """The generated project must have database configuration."""
        result = self._generate()
        db_file = os.path.join(result, "src", "infrastructure", "database.py")
        assert os.path.isfile(db_file), "database.py not found"


# ════════════════════════════════════════════════════════════════
# §9  REGRESSION — REST GENERATION STILL WORKS
# ════════════════════════════════════════════════════════════════

class TestRegressionREST:
    """Ensure AsyncAPI additions don't break existing OpenAPI/REST generation."""

    @pytest.fixture(autouse=True)
    def setup(self, tmp_path):
        self.output_dir = str(tmp_path / "rest_output")

    def test_openapi_project_still_generates(self):
        """A REST project.json should still generate correctly."""
        from apigen_copier.schemas import RESTProjectSchema, OpenApiProjectSchema, RouterSchema, EndpointSchema
        from apigen_copier.contracts import ModelContract, ModelAttribute, RelationalPersistence
        from apigen_copier.core import generate_from_schema

        project_info = OpenApiProjectSchema(
            name="Regression Test",
            version="0.0.1",
            description="Ensure REST still works",
            **{"data-driver": "postgresql"},
        )
        user_entity = ModelContract(
            relational_persistence=RelationalPersistence(table="users"),
            attributes=[
                ModelAttribute(name="id", type="Integer"),
                ModelAttribute(name="name", type="String"),
            ],
        )
        user_router = RouterSchema(
            entity="User",
            mapping="/users",
            endpoints=[EndpointSchema(method="get", name="getUsers", mapping="/")],
        )
        schema = RESTProjectSchema(
            project=project_info,
            entities={"User": user_entity},
            routers={"users": user_router},
            output_dir=self.output_dir,
        )

        result_path = generate_from_schema(schema)
        assert os.path.isdir(result_path), "REST generation failed"

    def test_generate_project_autodetects_rest(self):
        """generate_project() should still route REST project.json to the REST path."""
        from apigen_copier.core import generate_project

        # Create a minimal REST project.json file
        rest_data = {
            "project": {
                "name": "REST Test",
                "version": "1.0.0",
                "description": "Test",
                "data-driver": "postgresql",
            },
            "entities": {
                "Item": {
                    "table": "items",
                    "attributes": [
                        {"name": "id", "type": "Integer", "relational-persistence": {"primary-key": True}},
                        {"name": "title", "type": "String"},
                    ],
                }
            },
            "routers": {
                "items": {
                    "entity": "Item",
                    "mapping": "/items",
                    "endpoints": [{"method": "get", "name": "getItems", "mapping": "/"}],
                }
            },
        }

        input_file = os.path.join(self.output_dir, "project.json")
        os.makedirs(self.output_dir, exist_ok=True)
        with open(input_file, "w") as f:
            json.dump(rest_data, f)

        output_path = os.path.join(self.output_dir, "output")
        generate_project(input_file, output_path)
        # generate_project doesn't return a path, check the output dir directly
        assert os.path.isdir(output_path), "REST autodetection via generate_project failed"
        # Verify it generated a REST project (has src/main.py inside project slug)
        rest_dirs = os.listdir(output_path)
        assert len(rest_dirs) > 0, "No REST project generated"
