"""Tests para correcciones del mapper template y entity template.

Verifica que el código generado:
1. Usa nombres de columna (snake_case) en inspect(entity).unloaded, no nombres del modelo (camelCase)
2. No incluye comentarios DEBUG en entities generadas
3. Smart Mapping genera json.dumps/json.loads correctamente
"""
import os
import pytest
from apigen_copier.schemas import RESTProjectSchema, OpenApiProjectSchema
from apigen_copier.contracts import ModelContract, ModelAttribute, RelationalPersistence
from apigen_copier.core import generate_from_schema


OUTPUT_PATH = os.path.join(os.getcwd(), "temp_mapper_test")
PROJECT_SLUG = "mapper_test"


@pytest.fixture(scope="module")
def generated_project():
    """Genera un proyecto con campos camelCase que mapean a columnas snake_case."""

    # Limpiar generación anterior
    import shutil
    if os.path.exists(OUTPUT_PATH):
        shutil.rmtree(OUTPUT_PATH)

    project_info = OpenApiProjectSchema(
        name="Mapper Test",
        version="0.0.1",
        description="Test para mapper unloaded fix",
        **{"data-driver": "postgresql"}
    )

    # Owner con firstName -> first_name, lastName -> last_name
    owner_model = ModelContract(
        persistence=RelationalPersistence(table="owners"),
        attributes=[
            ModelAttribute(
                name="id", type="Long",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(
                    column="id", primary_key=True, autogenerated=True
                ),
            ),
            ModelAttribute(
                name="firstName", type="String",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="first_name"),
            ),
            ModelAttribute(
                name="lastName", type="String",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="last_name"),
            ),
            ModelAttribute(
                name="email", type="String",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="email"),
            ),
        ],
    )

    # Address con zipCode -> zip_code
    address_model = ModelContract(
        persistence=RelationalPersistence(table="addresses"),
        attributes=[
            ModelAttribute(
                name="id", type="Long",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(
                    column="id", primary_key=True, autogenerated=True
                ),
            ),
            ModelAttribute(
                name="street", type="String",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="street"),
            ),
            ModelAttribute(
                name="zipCode", type="String",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="zip_code"),
            ),
        ],
    )

    # Pet con photoUrls Smart Mapping (array -> JSON string)
    pet_model = ModelContract(
        persistence=RelationalPersistence(table="pets"),
        attributes=[
            ModelAttribute(
                name="id", type="Long",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(
                    column="id", primary_key=True, autogenerated=True
                ),
            ),
            ModelAttribute(
                name="name", type="String",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="name"),
            ),
            ModelAttribute(
                name="photoUrls", type="String",
                is_array=True,
                is_exposed_in_schema=True,
                has_json_conversion=True,
                persistence=RelationalPersistence(column="photo_urls"),
            ),
        ],
    )

    schema = RESTProjectSchema(
        project=project_info,
        entities={"Owner": owner_model, "Address": address_model, "Pet": pet_model},
        routers={},
        output_dir=OUTPUT_PATH,
    )

    generate_from_schema(schema)

    base = os.path.join(OUTPUT_PATH, PROJECT_SLUG, "src")
    return base


def _read(generated_project, *path_parts):
    """Helper para leer un archivo generado."""
    full = os.path.join(generated_project, *path_parts)
    assert os.path.exists(full), f"Archivo no encontrado: {full}"
    return open(full).read()


class TestMapperUnloadedUsesSnakeCase:
    """El mapper debe usar nombres de columna (snake_case) en inspect(entity).unloaded."""

    def test_owner_first_name_unloaded_check(self, generated_project):
        content = _read(generated_project, "infrastructure", "mappers", "owner", "owner_mapper.py")

        # CORRECTO: usa "first_name" (snake_case, nombre de columna SQLAlchemy)
        assert '"first_name" not in inspect(entity).unloaded' in content, \
            "Mapper debe verificar 'first_name' (snake_case) en inspect(entity).unloaded"

        # INCORRECTO: no debe usar "firstName" (camelCase, nombre del modelo)
        assert '"firstName" not in inspect(entity).unloaded' not in content, \
            "Mapper NO debe verificar 'firstName' (camelCase) en inspect(entity).unloaded"

    def test_owner_last_name_unloaded_check(self, generated_project):
        content = _read(generated_project, "infrastructure", "mappers", "owner", "owner_mapper.py")

        assert '"last_name" not in inspect(entity).unloaded' in content, \
            "Mapper debe verificar 'last_name' en inspect(entity).unloaded"
        assert '"lastName" not in inspect(entity).unloaded' not in content, \
            "Mapper NO debe verificar 'lastName' en inspect(entity).unloaded"

    def test_address_zip_code_unloaded_check(self, generated_project):
        content = _read(generated_project, "infrastructure", "mappers", "address", "address_mapper.py")

        assert '"zip_code" not in inspect(entity).unloaded' in content, \
            "Mapper debe verificar 'zip_code' en inspect(entity).unloaded"
        assert '"zipCode" not in inspect(entity).unloaded' not in content, \
            "Mapper NO debe verificar 'zipCode' en inspect(entity).unloaded"

    def test_same_name_field_unchanged(self, generated_project):
        """Cuando nombre del modelo == nombre de columna, no debe afectar."""
        content = _read(generated_project, "infrastructure", "mappers", "owner", "owner_mapper.py")

        assert '"email" not in inspect(entity).unloaded' in content, \
            "Campo 'email' (mismo nombre) debe funcionar igual"


class TestEntityNoDebugComments:
    """Las entities generadas no deben contener comentarios DEBUG."""

    def test_pet_entity_no_debug(self, generated_project):
        content = _read(generated_project, "infrastructure", "entities", "pet", "pet_entity.py")
        assert "# DEBUG:" not in content, \
            "Entity generada no debe contener líneas '# DEBUG:'"

    def test_owner_entity_no_debug(self, generated_project):
        content = _read(generated_project, "infrastructure", "entities", "owner", "owner_entity.py")
        assert "# DEBUG:" not in content, \
            "Entity generada no debe contener líneas '# DEBUG:'"

    def test_address_entity_no_debug(self, generated_project):
        content = _read(generated_project, "infrastructure", "entities", "address", "address_entity.py")
        assert "# DEBUG:" not in content, \
            "Entity generada no debe contener líneas '# DEBUG:'"


class TestSmartMappingGeneration:
    """Smart Mapping debe generar json.dumps/json.loads en el mapper."""

    def test_mapper_has_json_imports(self, generated_project):
        content = _read(generated_project, "infrastructure", "mappers", "pet", "pet_mapper.py")
        assert "import json" in content, "Mapper con Smart Mapping debe importar json"

    def test_mapper_has_json_loads_for_read(self, generated_project):
        content = _read(generated_project, "infrastructure", "mappers", "pet", "pet_mapper.py")
        assert "json.loads" in content or "_safe_json_loads" in content, \
            "Mapper debe usar json.loads o _safe_json_loads para leer photoUrls"

    def test_mapper_has_json_dumps_for_write(self, generated_project):
        content = _read(generated_project, "infrastructure", "mappers", "pet", "pet_mapper.py")
        assert "json.dumps" in content, \
            "Mapper debe usar json.dumps para escribir photoUrls"

    def test_photo_urls_uses_persistence_column(self, generated_project):
        """Smart Mapping accede directo a entity.photo_urls (columna snake_case)."""
        content = _read(generated_project, "infrastructure", "mappers", "pet", "pet_mapper.py")
        # Smart Mapping usa acceso directo con entity.photo_urls (no el patrón unloaded)
        assert "entity.photo_urls" in content, \
            "photoUrls debe leer entity.photo_urls (columna snake_case)"
        assert "entity.photoUrls" not in content, \
            "No debe acceder entity.photoUrls (camelCase)"
