"""
Tests for partial generation support.

Verifies that specs with some paths missing x-apigen-binding
are handled gracefully — only bound paths are generated.
"""
import os
import pytest
from apigen_copier.parser import OpenAPIParser


SPEC_PARTIAL = """
openapi: 3.0.0
info:
  title: Partial Gen Test
  version: 1.0.0
x-apigen-project:
  name: Partial Gen Test
  version: 1.0.0
  description: Test partial generation
  data-driver: postgresql
paths:
  /pets:
    x-apigen-binding:
      model: Pet
    get:
      operationId: listPets
      responses:
        '200':
          description: OK
    post:
      operationId: createPet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetCreate'
      responses:
        '201':
          description: Created
  /pets/{id}:
    x-apigen-binding:
      model: Pet
    get:
      operationId: getPetById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetGet'
  /health:
    get:
      operationId: healthCheck
      responses:
        '200':
          description: OK
  /docs:
    get:
      operationId: getDocs
      responses:
        '200':
          description: Documentation
components:
  x-apigen-models:
    Pet:
      relational-persistence:
        table: pets
      attributes:
        - name: id
          type: String
          relational-persistence:
            primary-key: true
            autogenerated: true
        - name: name
          type: String
        - name: status
          type: String
  schemas:
    PetGet:
      x-apigen-mapping:
        model: Pet
        method: get
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
    PetCreate:
      x-apigen-mapping:
        model: Pet
        method: post
      type: object
      properties:
        name:
          type: string
        status:
          type: string
"""

SPEC_NO_MODELS = """
openapi: 3.0.0
info:
  title: No Models Test
  version: 1.0.0
x-apigen-project:
  name: No Models Test
  version: 1.0.0
  data-driver: postgresql
paths:
  /health:
    get:
      operationId: healthCheck
      responses:
        '200':
          description: OK
  /users:
    get:
      operationId: listUsers
      responses:
        '200':
          description: OK
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
"""


class TestPartialGeneration:

    def _write_spec(self, tmp_path, content, filename="spec.yaml"):
        spec_path = os.path.join(str(tmp_path), filename)
        with open(spec_path, "w") as f:
            f.write(content)
        return spec_path

    def test_only_bound_paths_generate_routers(self, tmp_path):
        """Paths without x-apigen-binding should be silently skipped."""
        spec_path = self._write_spec(tmp_path, SPEC_PARTIAL)
        parser = OpenAPIParser(spec_path)

        # Only Pet router should exist (from /pets which has binding)
        assert "Pet" in parser.routers, "Pet router should be created"
        assert len(parser.routers) == 1, f"Expected 1 router, got {len(parser.routers)}"

        # /health and /docs should NOT create routers
        router_entities = [r.entity for r in parser.routers.values()]
        assert "Health" not in router_entities
        assert "Docs" not in router_entities

    def test_bound_paths_have_correct_endpoints(self, tmp_path):
        """Bound paths should generate all their endpoints normally."""
        spec_path = self._write_spec(tmp_path, SPEC_PARTIAL)
        parser = OpenAPIParser(spec_path)

        pet_router = parser.routers["Pet"]
        methods = [ep.method for ep in pet_router.endpoints]

        assert "GET" in methods, "GET /pets should be generated"
        assert "POST" in methods, "POST /pets should be generated"

    def test_no_models_no_crash(self, tmp_path):
        """A spec with no x-apigen-models should not crash — just produce empty routers."""
        spec_path = self._write_spec(tmp_path, SPEC_NO_MODELS)
        parser = OpenAPIParser(spec_path)

        # No routers since no bindings and no models
        assert len(parser.routers) == 0, "No routers should be created without models+bindings"

    def test_models_are_correct(self, tmp_path):
        """Models from x-apigen-models should be parsed even if some paths lack binding."""
        spec_path = self._write_spec(tmp_path, SPEC_PARTIAL)
        parser = OpenAPIParser(spec_path)

        assert "Pet" in parser.models, "Pet model should be parsed"
        pet_model = parser.models["Pet"]
        attr_names = [a.name for a in pet_model.attributes]
        assert "id" in attr_names
        assert "name" in attr_names
        assert "status" in attr_names
