"""Tests para issues encontrados en remote_test.

Verifica que el código generado:
1. ISSUE-002: POST response_model usa el schema correcto (PetGet, no PetPost)
2. ISSUE-003: _entity_to_full_dict excluye FK columns al expandir
3. ISSUE-004: No hay clases duplicadas en los routes generados
"""
import os
import re
import pytest
from apigen_copier.schemas import (
    RESTProjectSchema, OpenApiProjectSchema, RouterSchema,
    EndpointSchema, ResponseSchema, ResponseAttribute, RequestSchema,
)
from apigen_copier.contracts import ModelContract, ModelAttribute, RelationalPersistence
from apigen_copier.core import generate_from_schema


OUTPUT_PATH = os.path.join(os.getcwd(), "temp_route_issues_test")
PROJECT_SLUG = "route_issues_test"


@pytest.fixture(scope="module")
def generated_project():
    """Genera un proyecto con PetGet, PetPost, PetPut y relaciones para test."""
    import shutil
    if os.path.exists(OUTPUT_PATH):
        shutil.rmtree(OUTPUT_PATH)

    project_info = OpenApiProjectSchema(
        name="Route Issues Test",
        version="0.0.1",
        description="Test para route issues",
        **{"data-driver": "postgresql"}
    )

    # Address model
    address_model = ModelContract(
        persistence=RelationalPersistence(table="addresses"),
        attributes=[
            ModelAttribute(
                name="id", type="Long",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="id", primary_key=True, autogenerated=True),
            ),
            ModelAttribute(
                name="street", type="String",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="street"),
            ),
            ModelAttribute(
                name="city", type="String",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="city"),
            ),
        ],
    )

    # Category model
    category_model = ModelContract(
        persistence=RelationalPersistence(table="categories"),
        attributes=[
            ModelAttribute(
                name="id", type="Long",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="id", primary_key=True, autogenerated=True),
            ),
            ModelAttribute(
                name="name", type="String",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="name"),
            ),
        ],
    )

    # Owner model con address relation
    owner_model = ModelContract(
        persistence=RelationalPersistence(table="owners"),
        attributes=[
            ModelAttribute(
                name="id", type="Long",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="id", primary_key=True, autogenerated=True),
            ),
            ModelAttribute(
                name="firstName", type="String",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="first_name"),
            ),
            ModelAttribute(
                name="address", type="Relation",
                ref_model="Address",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="address_id", foreign_column="id"),
            ),
        ],
    )

    # Pet model con category y owner relations
    pet_model = ModelContract(
        persistence=RelationalPersistence(table="pets"),
        attributes=[
            ModelAttribute(
                name="id", type="Long",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="id", primary_key=True, autogenerated=True),
            ),
            ModelAttribute(
                name="name", type="String",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="name"),
            ),
            ModelAttribute(
                name="status", type="String",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="status"),
            ),
            ModelAttribute(
                name="category", type="Relation",
                ref_model="Category",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="category_id", foreign_column="id"),
            ),
            ModelAttribute(
                name="owner", type="Relation",
                ref_model="Owner",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="owner_id", foreign_column="id"),
            ),
            ModelAttribute(
                name="petsTags", type="Relation",
                ref_model="PetsTags",
                is_exposed_in_schema=False,
                is_array=True,
                items_ref_model="PetsTags",
                persistence=RelationalPersistence(foreign_column="pet_id"),
            ),
        ],
    )

    # Tags model
    tags_model = ModelContract(
        persistence=RelationalPersistence(table="tags"),
        attributes=[
            ModelAttribute(
                name="id", type="Long",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="id", primary_key=True, autogenerated=True),
            ),
            ModelAttribute(
                name="name", type="String",
                is_exposed_in_schema=True,
                persistence=RelationalPersistence(column="name"),
            ),
        ],
    )

    # PetsTags join table — composite PK on FK columns (set by parser's _ensure_join_table_pks)
    pets_tags_model = ModelContract(
        persistence=RelationalPersistence(table="pets_tags"),
        attributes=[
            ModelAttribute(
                name="pet", type="Relation",
                ref_model="Pet",
                is_exposed_in_schema=False,
                persistence=RelationalPersistence(column="pet_id", foreign_column="id", primary_key=True),
            ),
            ModelAttribute(
                name="tag", type="Relation",
                ref_model="Tags",
                is_exposed_in_schema=False,
                persistence=RelationalPersistence(column="tag_id", foreign_column="id", primary_key=True),
            ),
        ],
    )

    # PetGet response — excludes FK fields, includes relations as objects
    pet_get_response = ResponseSchema(attributes=[
        ResponseAttribute(name="id", type="Long"),
        ResponseAttribute(name="name", type="String"),
        ResponseAttribute(name="status", type="String"),
        ResponseAttribute(name="category", type="Relation", entity_field_name="category", ref_model="Category"),
        ResponseAttribute(name="owner", type="Relation", entity_field_name="owner", ref_model="Owner"),
    ])

    # PetPost response — includes FK fields, no relations
    pet_post_response = ResponseSchema(attributes=[
        ResponseAttribute(name="id", type="Long"),
        ResponseAttribute(name="name", type="String"),
        ResponseAttribute(name="status", type="String"),
        ResponseAttribute(name="categoryId", type="Long"),
        ResponseAttribute(name="ownerId", type="Long"),
    ])

    # Router con GET (lista), GET (by id), POST, PUT, DELETE
    pet_router = RouterSchema(
        entity="Pet",
        mapping="/pet",
        endpoints=[
            EndpointSchema(
                method="GET", name="listPets", mapping="",
                response=pet_get_response,
                response_schema_name="PetGet",
                parameters=[
                    {"name": "select", "in": "query", "required": False, "type": "string", "schema": {"type": "string"}},
                    {"name": "orderby", "in": "query", "required": False, "type": "string", "schema": {"type": "string"}},
                    {"name": "expand", "in": "query", "required": False, "type": "string", "schema": {"type": "string"}},
                ],
                responses={200: {"description": "successful operation", "content": {"application/json": {"schema": {"type": "array", "items": {"$ref": "#/components/schemas/PetGet"}}}}}},
            ),
            EndpointSchema(
                method="POST", name="addPet", mapping="",
                response=pet_get_response,  # POST should respond with PetGet
                response_schema_name="PetGet",  # Correct: response is PetGet
                responses={200: {"description": "Successful operation", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/PetGet"}}}}},
            ),
            EndpointSchema(
                method="PUT", name="updatePet", mapping="",
                response=pet_get_response,
                response_schema_name="PetGet",
                responses={200: {"description": "Successful operation", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/PetGet"}}}}},
            ),
            EndpointSchema(
                method="GET", name="getPetById", mapping="/{petId}",
                response=pet_get_response,
                response_schema_name="PetGet",
                parameters=[
                    {"name": "petId", "in": "path", "required": True, "type": "integer", "schema": {"type": "integer"}},
                    {"name": "select", "in": "query", "required": False, "type": "string", "schema": {"type": "string"}},
                    {"name": "expand", "in": "query", "required": False, "type": "string", "schema": {"type": "string"}},
                ],
                responses={200: {"description": "successful operation", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/PetGet"}}}}},
            ),
            EndpointSchema(
                method="DELETE", name="deletePet", mapping="/{petId}",
                parameters=[{"name": "petId", "in": "path", "required": True, "type": "integer", "schema": {"type": "integer"}}],
                responses={200: {"description": "Pet deleted"}},
            ),
        ],
        sub_routers={
            "findByStatus": RouterSchema(
                entity="Pet",
                mapping="/findByStatus",
                endpoints=[
                    EndpointSchema(
                        method="GET", name="findPetsByStatus", mapping="",
                        response=pet_get_response,
                        response_schema_name="PetGet",
                        parameters=[
                            {"name": "select", "in": "query", "required": False, "type": "string", "schema": {"type": "string"}},
                            {"name": "orderby", "in": "query", "required": False, "type": "string", "schema": {"type": "string"}},
                            {"name": "expand", "in": "query", "required": False, "type": "string", "schema": {"type": "string"}},
                        ],
                        responses={200: {"description": "successful operation"}},
                    ),
                ],
            ),
            "logout": RouterSchema(
                entity="Pet",
                mapping="/logout",
                endpoints=[
                    EndpointSchema(
                        method="GET", name="logoutPet", mapping="",
                        responses={200: {"description": "successful operation"}},
                    ),
                ],
            ),
            "find-by-tags": RouterSchema(
                entity="Pet",
                mapping="/find-by-tags",
                endpoints=[
                    EndpointSchema(
                        method="GET", name="findPetsByTags", mapping="",
                        response=pet_get_response,
                        response_schema_name="PetGet",
                        responses={200: {"description": "successful operation"}},
                    ),
                ],
            ),
        },
    )

    schema = RESTProjectSchema(
        project=project_info,
        entities={
            "Address": address_model,
            "Category": category_model,
            "Owner": owner_model,
            "Pet": pet_model,
            "Tags": tags_model,
            "PetsTags": pets_tags_model,
        },
        routers={"Pet": pet_router},
        output_dir=OUTPUT_PATH,
    )

    generate_from_schema(schema)
    base = os.path.join(OUTPUT_PATH, PROJECT_SLUG, "src")
    return base


def _read(generated_project, *path_parts):
    """Helper para leer un archivo generado."""
    full = os.path.join(generated_project, *path_parts)
    assert os.path.exists(full), f"Archivo no encontrado: {full}"
    return open(full).read()


# =============================================================================
# ISSUE-004: No duplicate class definitions in generated routes
# =============================================================================
class TestNoDuplicateClasses:
    """ISSUE-004: No debe haber clases duplicadas en las routes generadas."""

    def test_no_duplicate_pet_get_class(self, generated_project):
        """PetGet class must appear exactly once in pet_routes.py."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        matches = re.findall(r'^class PetGet\b', content, re.MULTILINE)
        assert len(matches) == 1, \
            f"PetGet class defined {len(matches)} times, expected 1"

    def test_local_nested_classes_exist(self, generated_project):
        """Response-local Owner and Category classes must be defined in the route file."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        assert re.search(r'^class Owner\b', content, re.MULTILINE), \
            "Local Owner response class should be defined in pet_routes.py"
        assert re.search(r'^class Category\b', content, re.MULTILINE), \
            "Local Category response class should be defined in pet_routes.py"

    def test_no_domain_model_imports_for_nested(self, generated_project):
        """Route file should NOT import domain models for nested response types."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        assert "from src.domain.models.owner" not in content, \
            "Should not import Owner domain model — local response class should be used"
        assert "from src.domain.models.category" not in content, \
            "Should not import Category domain model — local response class should be used"


# =============================================================================
# ISSUE-002: POST/PUT response_model must use PetGet (not PetPost/PetPut)
# =============================================================================
class TestPostResponseModel:
    """ISSUE-002: POST endpoint debe usar response_model correcto."""

    def test_post_endpoint_uses_pet_get_response_model(self, generated_project):
        """The @router.post line must use response_model=PetGet, not PetPost."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        # Find the @router.post line
        post_lines = [line for line in content.split('\n') if '@router.post(' in line]
        assert len(post_lines) >= 1, "No @router.post found"
        post_line = post_lines[0]
        # Must contain PetGet as response_model
        assert "response_model=PetGet" in post_line, \
            f"POST response_model should be PetGet, got: {post_line}"
        assert "response_model=PetPost" not in post_line, \
            f"POST response_model should NOT be PetPost, got: {post_line}"

    def test_put_endpoint_uses_pet_get_response_model(self, generated_project):
        """The @router.put line must use response_model=PetGet."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        put_lines = [line for line in content.split('\n') if '@router.put(' in line]
        assert len(put_lines) >= 1, "No @router.put found"
        put_line = put_lines[0]
        assert "response_model=PetGet" in put_line, \
            f"PUT response_model should be PetGet, got: {put_line}"

    def test_no_pet_post_class_generated(self, generated_project):
        """PetPost class should NOT be generated since it's not used as response."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        matches = re.findall(r'^class PetPost\b', content, re.MULTILINE)
        assert len(matches) == 0, \
            f"PetPost class should NOT be in routes (it's a request schema, not response)"


# =============================================================================
# ISSUE-003: Response model is the sole filter for FK/Relation fields
# =============================================================================
class TestResponseModelFiltering:
    """ISSUE-003 / ISSUE-022: local nested response classes include relations for expand L2+."""

    def test_local_owner_includes_relations_for_expand(self, generated_project):
        """ISSUE-022: Local Owner class in pet_routes should include relation fields for expand L2+."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        # Find the local Owner class
        owner_start = content.find("class Owner(BaseModel):")
        assert owner_start != -1, "Local Owner class not found in pet_routes.py"
        # Find end of class (next class def or end of file)
        next_class = content.find("\nclass ", owner_start + 10)
        owner_body = content[owner_start:next_class] if next_class != -1 else content[owner_start:]
        # Owner should have scalar fields AND relations (for expand L2+)
        assert "firstName" in owner_body, "Owner should have firstName field"
        assert "address" in owner_body, \
            "Owner response class SHOULD include 'address' (relations included for expand L2+)"

    def test_local_nested_class_has_only_scalar_fields(self, generated_project):
        """Local Category class should have only exposed, non-relation fields."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        cat_start = content.find("class Category(BaseModel):")
        assert cat_start != -1, "Local Category class not found"
        next_class = content.find("\nclass ", cat_start + 10)
        cat_body = content[cat_start:next_class] if next_class != -1 else content[cat_start:]
        assert "id" in cat_body, "Category should have id field"
        assert "name" in cat_body, "Category should have name field"


class TestMapperImportSyntax:
    """ISSUE-014 regression: mapper entity import must not concatenate with child mapper import."""

    def test_mapper_entity_import_on_own_line(self, generated_project):
        """Entity import line must end with newline, not merge with next mapper import."""
        # Pet mapper has child relations (photoUrls, orders, petsTags) → child mapper imports
        content = _read(generated_project, "infrastructure", "mappers", "pet", "pet_mapper.py")
        for line in content.splitlines():
            assert "Model" not in line or "Mapper" not in line, \
                f"Entity import and mapper import concatenated on same line: {line!r}"

    def test_all_mapper_files_compile(self, generated_project):
        """All mapper files must be valid Python (no SyntaxError)."""
        import py_compile
        mappers_dir = os.path.join(generated_project, "src", "infrastructure", "mappers")
        for root, _dirs, files in os.walk(mappers_dir):
            for fname in files:
                if fname.endswith("_mapper.py"):
                    path = os.path.join(root, fname)
                    try:
                        py_compile.compile(path, doraise=True)
                    except py_compile.PyCompileError as e:
                        pytest.fail(f"SyntaxError in {fname}: {e}")


class TestJoinTablePK:
    """ISSUE-010 regression: join table entities need composite PK on FK columns."""

    def test_join_table_fk_columns_have_primary_key(self, generated_project):
        """PetsTags entity FK columns should have primary_key=True."""
        content = _read(generated_project, "infrastructure", "entities", "petstags", "petstags_entity.py")
        # Both FK columns should be primary keys
        assert "primary_key=True" in content, \
            "Join table entity should have at least one primary_key=True column"
        pk_lines = [l for l in content.splitlines() if "primary_key=True" in l]
        assert len(pk_lines) == 2, \
            f"Expected 2 composite PK columns in join table, got {len(pk_lines)}: {pk_lines}"


class TestConditionalImport:
    """ISSUE-012 regression: subrouters without POST/PUT should not import domain model."""

    def test_get_only_subrouter_no_domain_import(self, generated_project):
        """A route file with only GET endpoints should not import _XxxInput."""
        # findbystatus is a GET-only subrouter
        content = _read(generated_project, "api", "routes", "pet", "findbystatus", "findbystatus_routes.py")
        assert "as _" not in content or "Input" not in content, \
            "GET-only subrouter should not import _XxxInput domain model"


class TestActionEndpoint:
    """ISSUE-013 regression: GET without response content should be an action, not GET-all."""

    def test_action_endpoint_no_pagination(self, generated_project):
        """logoutPet (GET, no response content) should NOT have pagination params."""
        content = _read(generated_project, "api", "routes", "pet", "logout", "logout_routes.py")
        assert "limit" not in content, "Action endpoint should not have limit param"
        assert "offset" not in content, "Action endpoint should not have offset param"
        assert "orderby" not in content, "Action endpoint should not have orderby param"

    def test_action_endpoint_no_expand(self, generated_project):
        """logoutPet should NOT have expand param."""
        content = _read(generated_project, "api", "routes", "pet", "logout", "logout_routes.py")
        assert "expand" not in content, "Action endpoint should not have expand param"

    def test_action_endpoint_response_model_none(self, generated_project):
        """logoutPet should have response_model=None."""
        content = _read(generated_project, "api", "routes", "pet", "logout", "logout_routes.py")
        assert "response_model=None" in content, "Action endpoint should have response_model=None"

    def test_action_endpoint_no_domain_import(self, generated_project):
        """logoutPet should NOT import domain model."""
        content = _read(generated_project, "api", "routes", "pet", "logout", "logout_routes.py")
        assert "_PetInput" not in content, "Action endpoint should not import domain model"


class TestSmartExpandSelect:
    """ISSUE-013 smart expand/select: only add expand when response has relations,
    select when response has entity fields."""

    def test_get_by_id_with_relations_has_expand(self, generated_project):
        """GET /{petId} response has Relation attrs → expand param should be present."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        # Find the getPetById function and its full parameter block
        idx = content.find("async def getPetById")
        assert idx != -1, "getPetById not found"
        # Find the closing "):" that ends the function signature
        end_idx = content.find("):", idx)
        assert end_idx != -1, "getPetById signature end not found"
        signature = content[idx:end_idx]
        assert "expand" in signature, "GET-by-id with relations should have expand param"
        assert "select" in signature, "GET-by-id with entity fields should have select param"

    def test_get_by_id_with_relations_passes_expand(self, generated_project):
        """GET-by-id handler should pass expand= to service.get_by_id()."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        assert "expand=expand" in content, "GET-by-id should pass expand to service"

    def test_action_endpoint_no_select(self, generated_project):
        """Action endpoint (logoutPet) should NOT have select param."""
        content = _read(generated_project, "api", "routes", "pet", "logout", "logout_routes.py")
        assert "select" not in content, "Action endpoint should not have select param"

    def test_subrouter_with_relations_has_expand(self, generated_project):
        """findByStatus response has Relation attrs → expand should be present."""
        content = _read(generated_project, "api", "routes", "pet", "findbystatus", "findbystatus_routes.py")
        assert "expand" in content, "Subrouter with relations should have expand param"
        assert "select" in content, "Subrouter with entity fields should have select param"


class TestHyphenatedSubrouter:
    """ISSUE-016 regression: hyphenated path segments must produce valid Python identifiers."""

    def test_hyphen_dir_uses_underscore(self, generated_project):
        """find-by-tags subrouter should create find_by_tags/ directory (not find-by-tags/)."""
        dir_path = os.path.join(generated_project, "api", "routes", "pet", "find_by_tags")
        assert os.path.isdir(dir_path), \
            f"Expected directory 'find_by_tags/', got: {os.listdir(os.path.join(generated_project, 'api', 'routes', 'pet'))}"

    def test_hyphen_filename_uses_underscore(self, generated_project):
        """Route file should be find_by_tags_routes.py (not find-by-tags_routes.py)."""
        fp = os.path.join(generated_project, "api", "routes", "pet", "find_by_tags", "find_by_tags_routes.py")
        assert os.path.isfile(fp), "Expected find_by_tags_routes.py file"

    def test_hyphen_import_uses_underscore(self, generated_project):
        """Parent route file should import with underscores, not hyphens."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        # Python import line must use underscores
        assert "from .find_by_tags.find_by_tags_routes" in content, \
            "Import path should use underscores"
        assert "find_by_tags_router" in content, \
            "Router variable should use underscores"

    def test_hyphen_route_compiles(self, generated_project):
        """The generated file for hyphenated subrouter must be valid Python."""
        fp = os.path.join(generated_project, "api", "routes", "pet", "find_by_tags", "find_by_tags_routes.py")
        if os.path.exists(fp):
            import py_compile
            try:
                py_compile.compile(fp, doraise=True)
            except py_compile.PyCompileError:
                pytest.fail("find_by_tags_routes.py has a SyntaxError")


class TestSubrouterOrdering:
    """ISSUE-017 regression: literal subrouters must be registered before parametrized endpoints."""

    def test_include_router_before_parametrized_endpoints(self, generated_project):
        """include_router() calls should appear before async def with path params."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        lines = content.split("\n")
        last_include = -1
        first_param_endpoint = len(lines)
        for i, line in enumerate(lines):
            if "include_router" in line:
                last_include = i
            if "async def" in line and "{" in content.split("\n")[i - 5:i + 5].__repr__():
                if "petId" in "".join(lines[max(0, i - 3):i + 3]):
                    first_param_endpoint = min(first_param_endpoint, i)
        if last_include > 0 and first_param_endpoint < len(lines):
            assert last_include < first_param_endpoint, \
                "include_router() must appear before parametrized endpoint definitions"


class TestStringPkPathParams:
    """ISSUE-019 regression: entities with String PKs should generate str path params."""

    def test_integer_pk_uses_int_param(self, generated_project):
        """Default fixture (Pet has Long PK) should still generate int path params."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        assert "petId: int = Path(...)" in content, \
            "Integer PK entity should generate 'int' path params"

    def test_string_pk_uses_str_param(self, tmp_path):
        """Entity with String PK should generate 'str' path params."""
        project_info = OpenApiProjectSchema(
            name="StringPkTest", version="0.0.1",
            description="Test", **{"data-driver": "postgresql"}
        )
        user_model = ModelContract(
            persistence=RelationalPersistence(table="users"),
            attributes=[
                ModelAttribute(
                    name="id", type="String",
                    is_exposed_in_schema=True,
                    persistence=RelationalPersistence(column="id", primary_key=True),
                ),
                ModelAttribute(
                    name="username", type="String",
                    is_exposed_in_schema=True,
                    persistence=RelationalPersistence(column="username"),
                ),
            ],
        )
        user_router = RouterSchema(
            entity="User", mapping="/users",
            endpoints=[
                EndpointSchema(
                    method="GET", name="getUserById", mapping="/{userId}",
                    parameters=[{"name": "userId", "in": "path", "required": True, "type": "integer", "schema": {"type": "integer"}}],
                    responses={200: {"description": "ok"}},
                ),
            ],
        )
        schema = RESTProjectSchema(
            project=project_info,
            entities={"User": user_model},
            routers={"User": user_router},
            output_dir=str(tmp_path),
        )
        generate_from_schema(schema)
        slug = [d for d in os.listdir(str(tmp_path)) if os.path.isdir(os.path.join(str(tmp_path), d))][0]
        content = open(os.path.join(str(tmp_path), slug, "src", "api", "routes", "user", "user_routes.py")).read()
        assert "userId: str = Path(...)" in content, \
            "String PK entity should override path param type to 'str'"
        assert "userId: int" not in content, \
            "String PK entity must NOT use 'int' for path params"


class TestExpandL2NestedRelations:
    """ISSUE-022: expand level 2+ — nested classes con relaciones, AliasChoices y Smart Mapping."""

    def test_nested_class_has_alias_choices(self, generated_project):
        """Nested Owner class should use AliasChoices for camelCase/snakeCase resolution."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        assert 'AliasChoices("firstName", "first_name")' in content, \
            "Nested Owner should have AliasChoices for firstName/first_name"

    def test_nested_class_has_populate_by_name(self, generated_project):
        """Nested classes should have populate_by_name=True in ConfigDict."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        owner_start = content.find("class Owner(BaseModel):")
        assert owner_start != -1
        next_class = content.find("\nclass ", owner_start + 10)
        owner_body = content[owner_start:next_class] if next_class != -1 else content[owner_start:]
        assert "populate_by_name=True" in owner_body, \
            "Nested Owner class should have populate_by_name=True"

    def test_nested_class_has_model_rebuild(self, generated_project):
        """Nested classes should call model_rebuild() for forward reference resolution."""
        content = _read(generated_project, "api", "routes", "pet", "pet_routes.py")
        assert "Owner.model_rebuild()" in content, \
            "Nested Owner class should have model_rebuild() call"

    def test_domain_model_has_alias_choices(self, generated_project):
        """Domain model Owner should use AliasChoices for ORM attribute resolution."""
        content = _read(generated_project, "domain", "models", "owner", "owner_model.py")
        assert 'AliasChoices("firstName", "first_name")' in content, \
            "Domain Owner should have AliasChoices for firstName/first_name"

    def test_domain_model_has_populate_by_name(self, generated_project):
        """Domain model should have populate_by_name=True."""
        content = _read(generated_project, "domain", "models", "owner", "owner_model.py")
        assert "populate_by_name=True" in content, \
            "Domain Owner model should have populate_by_name=True"
