import json
import os
import shutil
import subprocess

def generate():
    base_path = os.path.dirname(os.path.abspath(__file__))
    resource_path = os.path.join(base_path, "../../resources/hospital_metadata.json")
    with open(resource_path, "r") as f:
        metadata = json.load(f)

    # template_config_path = os.path.join(base_path, "../../resources/MasterTemplate/cookiecutter.json")
    # We do not overwrite cookiecutter.json anymore.
    
    config = {
        "project_name": "Hospital API Cruft",
        "project_slug": "hospital_api_cruft",
        "description": "Generated by Cruft",
        "resources": {"resource_list": metadata["resources"]}
    }
    
    # Convert config to JSON string for CLI
    extra_context_str = json.dumps(config)

    template_path = os.path.join(base_path, "../../resources/MasterTemplate")
    output_dir = os.path.join(base_path, "output")
    
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)
    os.makedirs(output_dir)
    
    try:
        # Pass extra context as JSON string
        subprocess.run(f"cruft create {template_path} --no-input --output-dir {output_dir} --extra-context '{extra_context_str}'", shell=True, check=True)
    except subprocess.CalledProcessError:
        print("Cruft CLI failed (likely not a git repo). Fallback to CookieCutter.")
        # Fallback to cookiecutter with extra_context passed via command line? 
        # Cookiecutter CLI also supports extra_context but format might be different or key=value.
        # Actually cookiecutter CLI takes key=value pairs or a file.
        # But we can use the python library here since we are in python!
        from cookiecutter.main import cookiecutter
        cookiecutter(
            template_path,
            no_input=True,
            extra_context=config,
            output_dir=output_dir
        )
    print(f"Generado en: {output_dir}")

if __name__ == "__main__":
    generate()
