import json
import os
import shutil
from copier import run_copy

def generate():
    base_path = os.path.dirname(os.path.abspath(__file__))
    resource_path = os.path.join(base_path, "../../resources/hospital_metadata.json")
    with open(resource_path, "r") as f:
        metadata = json.load(f)

    # master_template_path removed
    copier_template_path = os.path.join(base_path, "CopierTemplate")
    
    # We assume CopierTemplate is already generated and ready to use.
    # We do NOT copy from MasterTemplate or regenerate copier.yml anymore.

    output_dir = os.path.join(base_path, "output")
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)
    
    data_dict = {
        "project_name": "Hospital API Copier",
        "project_slug": "hospital_api_copier",
        "description": "Generated by Copier",
        "resources": {"resource_list": metadata["resources"]}
    }
    
    run_copy(
        src_path=copier_template_path,
        dst_path=output_dir,
        data=data_dict,
        unsafe=True 
    )
    print(f"Generado en: {output_dir}")

if __name__ == "__main__":
    generate()
