import json
import os
import shutil
import subprocess
from cookiecutter.main import cookiecutter

def generate():
    base_path = os.path.dirname(os.path.abspath(__file__))
    resource_path = os.path.join(base_path, "../../resources/hospital_metadata.json")
    with open(resource_path, "r") as f:
        metadata = json.load(f)

    output_dir = os.path.join(base_path, "output")
    project_slug = "hospital_api_pyscaffold"
    full_path = os.path.join(output_dir, project_slug)
    
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)
    os.makedirs(output_dir)
    
    subprocess.run(f"putup {full_path} --force", shell=True, check=True)

    # template_config_path removed as it is unused
    # We do not overwrite cookiecutter.json anymore.
    
    config = {
        "project_name": "Hospital API PyScaffold",
        "project_slug": "hospital_api_pyscaffold",
        "description": "Generated by PyScaffold",
        "resources": {"resource_list": metadata["resources"]}
    }

    template_path = os.path.join(base_path, "../../resources/MasterTemplate")
    temp_cc_dir = os.path.join(base_path, "temp_overlay")
    
    if os.path.exists(temp_cc_dir):
        shutil.rmtree(temp_cc_dir)
        
    cookiecutter(
        template_path,
        no_input=True,
        extra_context=config,
        output_dir=temp_cc_dir
    )
    
    cc_src = os.path.join(temp_cc_dir, project_slug, "src")
    ps_src = os.path.join(full_path, "src", project_slug)
    
    if os.path.exists(cc_src):
        for item in os.listdir(cc_src):
            s = os.path.join(cc_src, item)
            d = os.path.join(ps_src, item)
            if os.path.isdir(s):
                if os.path.exists(d):
                    shutil.rmtree(d)
                shutil.copytree(s, d)
            else:
                shutil.copy2(s, d)
                
    cc_req = os.path.join(temp_cc_dir, project_slug, "requirements.txt")
    ps_req = os.path.join(full_path, "requirements.txt")
    if os.path.exists(cc_req):
        shutil.copy2(cc_req, ps_req)
        
    shutil.rmtree(temp_cc_dir)
    print(f"Generado en: {output_dir}")

if __name__ == "__main__":
    generate()
