import json
import os
import shutil
from cookiecutter.main import cookiecutter

def generate():
    base_path = os.path.dirname(os.path.abspath(__file__))
    resource_path = os.path.join(base_path, "../../resources/hospital_metadata.json")
    with open(resource_path, "r") as f:
        metadata = json.load(f)

    # template_config_path removed as it is unused
    # We do not overwrite cookiecutter.json anymore as per user request.
    # Instead we pass the config via extra_context.
    
    config = {
        "project_name": "Hospital API CookieCutter",
        "project_slug": "hospital_api_cookiecutter",
        "description": "Generated by CookieCutter",
        "resources": {"resource_list": metadata["resources"]}
    }

    template_path = os.path.join(base_path, "../../resources/MasterTemplate")
    output_dir = os.path.join(base_path, "output")
    
    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)
    os.makedirs(output_dir)
    
    cookiecutter(
        template_path,
        no_input=True,
        extra_context=config, 
        output_dir=output_dir
    )
    print(f"Generado en: {output_dir}")

if __name__ == "__main__":
    generate()
